# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pVmMBunIGM-xpLA9HhxB36h3U4v5aTv6
"""

#Priya Rajpurohit 2015073
#Sakshi Saini 2017092

from keras.models import Sequential
from keras.layers import Dense
from keras.models import model_from_json
import numpy
import os
import random
import cv2
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Path='/content/drive/My Drive/SML_Project/'
file1='Xception_final/labels_xception_seg.h5'
file2='Xception_final/model.json'
file3= 'Xception_final/segmented_xception.h5'
file4='Xception_final/model.h5'
file5="/content/drive/My Drive/SML_Project/Xception_final/xception_svm_model_seg.sav"

import h5py
hf = h5py.File(Path+file1, 'r')
labels= np.array(hf.get('dataset_1'))
hf.close()

hf1 = h5py.File(Path+file3, 'r')
features= np.array(hf1.get('dataset_1'))
hf1.close()

import pickle

model= pickle.load(open(file5, 'rb'))

im1=features[0]
res1=model.predict(im1.reshape(1,-1))

print("Actual label "+str(np.argmax(labels[0])))
print("predicted label "+str(res1))

im1.shape

X=features[:1000]
Y=[]
for i in range(1000):
  s=np.argmax(labels[i])
  Y.append(s)
Y=np.array(Y)

Y.shape

X_=[]
for i in range(1000):
  X_.append(X[i].reshape(1,-1).reshape(100352))
a=model.score(np.array(X_),Y)
print(a)

np.array(X_).shape

import pandas as pd 
  
y=pd.read_csv("/content/drive/My Drive/SML_Project/label.csv") 
score=0
for i in range(1000):
  label=model.predict(X_[i].reshape(1,-1))
  res1=Y[i]
  #print(label,res1)
  l1=y['label_name'].iloc[int(label)]
  l2=y['label_name'].iloc[int(res1)]
  #print(l1,str(l2))
  if 'healthy' in l1:
    x1='healthy'
  else:
    x1='diseased'
  if 'healthy' in str(l2):
    x2='healthy'
  else:
    x2='diseased'
  if x1==x2:
    score=score+1
print(score/1000)